# 데이터 수집

## 현재 작업 디렉토리 확인

In [2]:
import os
print(os.getcwd())

#작업 디렉토리를 변경
#os.chdir('변경할 디렉토리 경로')

C:\Users\tj


## Series

### Series를 직접 생성하고 속성 확인

In [6]:
#pandas 라는 모듈을 pd 라는 이름으로 가져온 것
import pandas as pd

#pandas 패키지의 Series 모듈을 현재 애플리케이션의 메모리로 가져와서 사용
#Series 앞에는 pandas.을 붙일 필요가 없습니다.
from pandas import Series


#list를 이용해서 Series를 생성
#index 를 설정하지 않아서 index는 0부터 시작하는 시퀀스
price = Series([4000, 3000, 2000, 1000])

#데이터 확인
print(price) #인덱스 와 값 그리고 dtype이 출력

#인덱스 확인
print(price.index)

#데이터를 확인
print(price.values)
print(type(price.values)) #자료형은 numpy 의 ndarray

#인덱스 변경
price.index = ['apple', 'mango', 'orange', 'kiwi']
print(price)

0    4000
1    3000
2    2000
3    1000
dtype: int64
RangeIndex(start=0, stop=4, step=1)
[4000 3000 2000 1000]
<class 'numpy.ndarray'>
apple     4000
mango     3000
orange    2000
kiwi      1000
dtype: int64


## Series 의 인덱싱

In [12]:
#pandas 라는 모듈을 pd 라는 이름으로 가져온 것
import pandas as pd

#pandas 패키지의 Series 모듈을 현재 애플리케이션의 메모리로 가져와서 사용
#Series 앞에는 pandas.을 붙일 필요가 없습니다.
from pandas import Series

sourcedata = {'suzi':29, 'irin':32, 'karina':23}
#dict 를 이용해서 Series를 생성
#dict를 가지고 생성하면 key 가 인덱스가 되고 value는 value 가 됩니다.
data = Series(sourcedata)
print(data)
print()

#데이터 1개 가져오기
print(data[0]) #0번 위치
print(data['suzi'])#suzi 라는 인덱스를 가진 데이터
print()

#범위 설정
print(data[0:2]) #0번 에서 2번 앞 까지
print(data['suzi':'karina'])#suzi 부터 karina 까지
print()

#Fancy Indexing - 복제가 발생
print(data[['suzi','karina']])
print()

#Boolean Indexing - True 인 데이터만 필터링
print(data[[True, False, False]])

suzi      29
irin      32
karina    23
dtype: int64

29
29

suzi    29
irin    32
dtype: int64
suzi      29
irin      32
karina    23
dtype: int64

suzi      29
karina    23
dtype: int64

suzi    29
dtype: int64


## Series 의 연산

In [15]:
#pandas 라는 모듈을 pd 라는 이름으로 가져온 것
import pandas as pd

#pandas 패키지의 Series 모듈을 현재 애플리케이션의 메모리로 가져와서 사용
#Series 앞에는 pandas.을 붙일 필요가 없습니다.
from pandas import Series

#하나의 list는 key 로 다른 하나의 list는 value 로 해서 dict를 생성
keys = ['park', 'bae', 'moon', 'lee']
values = [45, 56, 21, 34]
dict1 = dict(zip(keys, values))
#print(dict1)


keys = ['park', 'bae', 'moon', 'choi']
values = [32, None, 97, 34]
dict2 = dict(zip(keys, values))

s1 = Series(dict1)
s2 = Series(dict2)
#print(s1)
#print(s2)

print(s1 + s2) #lee 나 choi 인덱스는 한쪽에만 존재해서 NaN
#bae 는 하나의 데이터가 None 이라서 연산을 하면 NaN

bae       NaN
choi      NaN
lee       NaN
moon    118.0
park     77.0
dtype: float64


## DataFrame 

### dict를 가지고 DataFrame 생성

In [17]:
import pandas as pd

from pandas import Series, DataFrame

#4개의 key를 가진 dict를 생성
items = {
    'code' : [1,2,3,4,5,6],
    'name' : ['apple', 'watermelon', 'orientalmelon', 'banana', 'lemon','mango'],
    'manufacture' : ['korea', 'korea', 'korea', 'phillippines','korea', 'taiwan'],
    'price' : [1500, 2000, 1000, 3000, 1200, 2300]
}

df = DataFrame(items)

print(df)

#print(type(df))



   code           name   manufacture  price
0     1          apple         korea   1500
1     2     watermelon         korea   2000
2     3  orientalmelon         korea   1000
3     4         banana  phillippines   3000
4     5          lemon         korea   1200
5     6          mango        taiwan   2300
<class 'pandas.core.frame.DataFrame'>


In [22]:
import pandas as pd

from pandas import Series, DataFrame

#4개의 key를 가진 dict를 생성
items = {
    'code' : [1,2,3,4,5,6],
    'name' : ['apple', 'watermelon', 'orientalmelon', 'banana', 'lemon','mango'],
    'manufacture' : ['korea', 'korea', 'korea', 'phillippines','korea', 'taiwan'],
    'price' : [1500, 2000, 1000, 3000, 1200, 2300]
}

df = DataFrame(items)

#컬럼 이름 변경
df.columns = ['코드', '이름', '원산지', '가격']
#인덱스 변경
df.index = range(1,7,1)

#앞 3개의 데이터 확인
print(df.head(3))
#데이터 정보 확인
df.info()



   코드             이름    원산지    가격
1   1          apple  korea  1500
2   2     watermelon  korea  2000
3   3  orientalmelon  korea  1000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 1 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   코드      6 non-null      int64 
 1   이름      6 non-null      object
 2   원산지     6 non-null      object
 3   가격      6 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes
None


## 데이터 수집

### 클립보드 내용 복사

In [23]:
import pandas as pd
from pandas import Series, DataFrame


df = pd.read_clipboard()
print(df)

   code           name   manufacture  price
0     1          apple         korea   1500
1     2     watermelon         korea   2000
2     3  orientalmelon         korea   1000
3     4         banana  phillippines   3000
4     5          lemon         korea   1200
5     6          mango        taiwan   2300


### sklearn 의 boston 데이터 가져오기

In [28]:
import pandas as pd
from pandas import Series, DataFrame
#sklearn 의 데이터 import
from sklearn import datasets

boston = datasets.load_boston()
#dict 로 구성되어 있음
#print(boston)

#키의 이름 확인
#print(boston.keys())

#data 가 ndarray 타입의 데이터 이고 feature_names이 열 이름
print(boston.feature_names)

data = boston.data
print(type(data))
print(data)

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']
<class 'numpy.ndarray'>
[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


### fwf 파일 데이터 읽기

In [29]:
import pandas as pd
from pandas import Series, DataFrame

df = pd.read_fwf('./data/data_fwf.txt', widths=(10, 2, 5), 
                 names=('date', 'name', 'price'))
print(df)

         date name  price
0  2017-04-10   다음  32000
1  2017-04-11   다음  34000
2  2017-04-12   다음  33000


### csv 읽기

In [30]:
#item.csv 파일 읽기
import pandas as pd
from pandas import Series, DataFrame

items = pd.read_csv('./data/item.csv')
print(items)

   code  manufacture            name  price
0     1        korea           apple   1500
1     2        korea      watermelon  15000
2     3        korea  oriental melon   1000
3     4  philippines          banana    500
4     5        korea           lemon   1500
5     6        korea           mango    700


In [33]:
#good.csv 파일 읽기
import pandas as pd
from pandas import Series, DataFrame

items = pd.read_csv('./data/good.csv', header=None,
                    names=['이름', '개수', '가격'])
print(items)

       이름  개수     가격
0   apple  10   1500
1  banana   5  15000
2   melon   7   1000
3    kiwi  20    500
4   mango  30   1500
5  orange   4    700


In [35]:
#good.csv 파일의 데이터를 2개씩 읽기
import pandas as pd
from pandas import Series, DataFrame

items = pd.read_csv('./data/good.csv', header=None,
                    names=['이름', '개수', '가격'], chunksize=2)
for item in items:
    print(item)

       이름  개수     가격
0   apple  10   1500
1  banana   5  15000
      이름  개수    가격
2  melon   7  1000
3   kiwi  20   500
       이름  개수    가격
4   mango  30  1500
5  orange   4   700


### csv 저장

In [37]:
import pandas as pd

from pandas import Series, DataFrame

#4개의 key를 가진 dict를 생성
items = {
    'code' : [1,2,3,4,5,6],
    'name' : ['apple', 'watermelon', 'orientalmelon', 'banana', 'lemon','mango'],
    'manufacture' : ['korea', 'korea', 'korea', 'phillippines','korea', 'taiwan'],
    'price' : [1500, 2000, 1000, 3000, 1200, 2300]
}

df = DataFrame(items)
print(df)

#저장
df.to_csv('./data/pddata.csv', index=False)

   code           name   manufacture  price
0     1          apple         korea   1500
1     2     watermelon         korea   2000
2     3  orientalmelon         korea   1000
3     4         banana  phillippines   3000
4     5          lemon         korea   1200
5     6          mango        taiwan   2300


### 엑셀 파일 읽기 및 저장

In [40]:
import pandas as pd

from pandas import Series, DataFrame

#첫번째 열을 인덱스로 사용
df = pd.read_excel('./data/excel.xlsx', index_col=0)
print(df)

#현재 데이터를 파일로 저장
writer = pd.ExcelWriter('./data/0210.xlsx')
df.to_excel(writer, sheet_name="Sheet1")
writer.save()

                            이름   1과목   2과목   3과목
번호                                              
1                          이효준  40.0   NaN  45.0
2                          김성희  42.0  55.0  50.0
3                          이연숙   NaN  60.0  55.0
4                          노화현  50.0  70.0  60.0
5                          최희순  55.0  75.0   NaN
6                          정원주  60.0  80.0  70.0


### Web에서 가져오기

In [45]:
#HTML 페이지의 table 태그 내용 가져오기
import pandas as pd
from pandas import Series, DataFrame

li = pd.read_html('https://ko.wikipedia.org/wiki/%EC%9D%B8%EA%B5%AC%EC%88%9C_%EB%82%98%EB%9D%BC_%EB%AA%A9%EB%A1%9D')
                      
print(li[0])

       0        1           2       3                            4
0      1  중화인민공화국  1411718724  2021.0  공식 인구시계 세계에서 1번째로 인구가 많은 나라
1      2       인도  1379619774  2021.0                      공식 인구시계
2      3       미국   332915074  2020.0                      공식 인구시계
3      4    인도네시아   276361788  2020.0                      공식 인구시계
4      5     파키스탄   225199929  2020.0                      공식 인구시계
..   ...      ...         ...     ...                          ...
235  235      노퍽섬        1756     NaN                          NaN
236  236      니우에        1520     NaN                          NaN
237  237     토켈라우        1411     NaN                          NaN
238  238   바티칸 시국         825  2021.0                          NaN
239  239   핏케언 제도          47  2021.0            세계에서 가장 인구가 없는 나라

[240 rows x 5 columns]


In [52]:
#xml 파싱을 수행해서 DataFrame을 만들기
import pandas as pd
from pandas import Series, DataFrame

#웹에서 데이터를 가져오기 위한 패키지 - 파이썬의 기본 패키지
import urllib.request

#XML 파싱을 위한 패키지
import xml.etree.ElementTree as et

url = 'http://www.hani.co.kr/rss/sports'
request = urllib.request.Request(url)
response = urllib.request.urlopen(request)
#print(response.read())

#가져온 내용을 DOM 으로 펼쳐서 root를 찾아오기
tree = et.parse(response)
xroot = tree.getroot()
#print(xroot)

#channel 태그의 모든 것을 찾아오기
channel = xroot.findall('channel')
#print(channel)

#item 태그의 모든 것을 찾아괴
items = channel[0].findall('item')
#print(items)

rows = []
for node in items:
    title = node.find("title").text if node is not None else None
    link = node.find("link").text if node is not None else None
    #가져온 데이터를 dict로 만들어서 list에 추가
    rows.append({"title":title, "link":link})
    
df = pd.DataFrame(rows, columns=["title", "link"])
print(df)

[<Element 'channel' at 0x0000020ADCD13540>]
                                      title  \
0        ‘천재 소녀’에서 ‘살아있는 역사’로…클로이 킴 올림픽 2연패   
1               ‘바람의 스케이터’ 차준환, 세계 톱5 역사 썼다   
2           외부 요인은 사라졌다, 여자 쇼트 ‘금빛 질주’만 남았다   
3          스켈레톤 정승기, 올림픽 첫 무대서 10위…윤성빈은 12위   
4                    토트넘, 손흥민 득점포에도 역전패 아쉬움   
5       황대헌 “판정에서 한 수 배워…아무도 손 못 대는 전략 세웠다”   
6             판정, 빙질, 텃세… 무엇도 황대헌을 막을 수 없었다   
7                [포토] 황대헌, 베이징 ‘첫 금’ 거머쥔 순간   
8      역시 최민정! 딱 ‘반 바퀴’ 만에 계주 3000m 승부 뒤집었다   
9          완벽한 금빛 질주…황대헌, ‘쇼트트랙 강국’ 저력 증명했다   
10        한국 쇼트트랙 남자팀 전원 1500m 결승 진출…중국은 전멸   
11          최민정·이유빈 여자 1000m 준준결승 안착…김아랑 탈락   
12    ‘실력 봤지?’ 황대헌·이준서·박장혁 나란히 1500m 준결승 진출   
13    [아하 올림픽] 여자 피겨는 오후인데…남자 피겨는 왜 오전에 열릴까   
14        선수단, 국제빙상연맹에 재차 항의…“오늘 경기, 지켜보겠다”   
15  코로나 검사 45번·스케이트 분실…끝내 베이징 왔다 [올림픽 이모저모]   
16        ‘신공지능’ 별명 신진서, 6시간30분 격전 끝 LG배 정상   
17                   영미 대신 초희…‘팀 킴’의 시간이 왔다   
18       스노보드 퀸과 킹이 돌아왔다…클로이 킴, 숀 화이트 결선 진출   
19       알파인 최강자

### json

In [66]:
import pandas
from pandas import Series, DataFrame

df = pandas.read_json('http://swiftapi.rubypaper.co.kr:2029/hoppin/movies?version=1&page=1&count=30&genreId=&order=releasedateasc')
#print(df)

hoppin = df['hoppin']
#print(hoppin)

movies = hoppin['movies']
#print(movies)

movie = movies['movie']
#print(movie)


rows = []
for item in movie:
    #print(item['title'], ":", item['ratingAverage'])
    rows.append({'title':item['title'],
                 'ratingAverage':item['ratingAverage']})
    
df = DataFrame(rows)
df.columns = ['제목', '평점']
print(df)

                       제목   평점
0                    인포먼트  6.7
1              엣지 오브 다크니스  6.9
2                   베이비 돌    6
3                 황야의 역마차  6.3
4                  전원 교향곡    8
5                 아버지의 깃발    8
6                  여덟번의감정    6
7                      레드  8.7
8                  영광의 탈출  6.8
9                     크로싱  8.8
10                 맨 인 블랙  8.9
11                    차형사  8.4
12             에이지 오브 드래곤  3.9
13              로드 오브 워리어  7.4
14  [메이킹 다큐] 도둑들 영화를 만들다!  7.9
15               괜찮아요 수달씨  7.5
16                     파파    9
17                 이케맨 뱅크  6.7
18           다중인격소녀 ISOLA  5.7
19                   위조지폐  6.5
20                 카인과 아벨  6.9
21                  돌핀 블루  8.2
22                   더 코드  7.6
23             철권 블러드 벤전스    8
24       블루 엘리펀트 (우리말 더빙)  8.8
25             해결사 (2010)  8.3
26         하나오니 2: 사랑의 시작  8.5
27         하나오니 3: 복수의 시간  8.5
28         아테나 전쟁의 여신 극장판  7.7
29               아이스 프린세스  8.8


In [70]:
#orient 옵션 사용하기
import pandas
from pandas import Series, DataFrame

df = pandas.read_json('https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json')
df.info()
print(df.head())


<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   integer   100 non-null    int64         
 1   datetime  100 non-null    datetime64[ns]
 2   category  100 non-null    int64         
dtypes: datetime64[ns](1), int64(2)
memory usage: 3.1 KB
   integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0
2        9 2015-01-01 00:00:02         0
3        6 2015-01-01 00:00:03         0
4        6 2015-01-01 00:00:04         0


### yaml 사용

In [73]:
import yaml
with open('./data/vegetables.yml') as f:
    vegetables = yaml.load(f, Loader=yaml.FullLoader)
    print(vegetables)
    
    
fruits = {'fruits':['apple', 'pear', 'kiwi', 'orange']}   
with open('./data/fruits.yml', 'w') as f:
    yaml.dump(fruits, f)

{'Vegetables': ['Pepper', 'Tomato', 'Garlic']}
