#Numpy

In [5]:
import numpy as np
import datetime

#ndarray : numpy에서 제공하는 배열

#list 생성 - 0부터 999999까지
li = list(range(0, 1000000, 1))

#현재 시간을 가져오기
start = datetime.datetime.now()
print('리스트 작업 시작시간:', start)

#모든 데이터에 10을 곱해서 저장
for i in li:
    i * 10

end = datetime.datetime.now()
print('리스트 작업 종료시간:', end)
          
ar = np.arange(0, 1000000, 1)
          
#현재 시간을 가져오기
start = datetime.datetime.now()
print('배열 작업 시작시간:', start)

#모든 데이터에 10을 곱해서 저장
ar * 10

end = datetime.datetime.now()
print('배열 작업 종료시간:', end)

리스트 작업 시작시간: 2022-02-08 16:46:13.616077
리스트 작업 종료시간: 2022-02-08 16:46:13.702734
배열 작업 시작시간: 2022-02-08 16:46:13.704741
배열 작업 종료시간: 2022-02-08 16:46:13.707733


#특수행렬

In [13]:
import numpy as np
#1로 10을채운 배열 생성
ar1 = np.ones(10)
print(ar1)

#1로 채워진 5*5 배열 생성
ar2 = np.ones((5,5))
print(ar2)

#2*2정방행렬을 만들고 대각선 방향으로 1을 채운 행렬 생성
ar3 = np.eye(2)
print(ar3)

#1의 위치를 수정
ar4 = np.eye(3, k=1)
print(ar4)

ar5 = np.eye(3, k=2)
print(ar5)

#대각선에서 데이터를 추출해서 새로운 1차원 배열 생성
br = np.diag(ar4, k=1)
print(br)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0.]
 [0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1.]


#요소의 데이터 타입을 변경

In [18]:
import numpy as np

#type 설정해서 생성
ar = np.array([1, 2, 3])
print(ar.dtype)
      
br = np.array([1, 2, '3'])
print(br.dtype)
      
cr = np.array([1, 2, '3'], dtype=np.int32)
print(cr.dtype)
      
#type을 float32로 변경
ar = ar.astype(np.float32)
print(ar.dtype)

int32
<U11
int32
float32


행렬의 구조 변경

In [27]:
import numpy as np

#1차원 배열 생성
ar = np.arange(10)
print(ar)

#2차원 배열 생성
br = ar.reshape(2, 5)
print(br)

#2차원을 1차원 배열로 변환
print(br.reshape(-1))
print(br.flatten())


#1차원 배열 생성
ar = np.arange(20)
#print(ar.reshape(2,5)) #10개만 생성되므로 에러
#1차원 배열을 3차원으로 변환
print(ar.reshape(2, 5, 2))
#마지막 차원의 개수는 -1로  설정하면 알아서 분할해서 생성해 줍니다
print(ar.reshape(2, 5, -1))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


인덱싱 - 데이터의 일부분을 선택

In [6]:
import numpy as np

ar = np.array([100, 200, 300, 400, 500])

#1차원 배열 생성한 후 4*5의 2차원 배열로 변환
matrix = np.array(range(1, 21)).reshape(4,5)
print(matrix)

#2차원 배열에서 하나의 요소를 추출
print(matrix[1, 2])
print(matrix[1][2])

#2차원 배열에서 하나의 인덱스를 대입해서 추출 - 1행 전체
print(matrix[1])

#특정위치부터 끝까지
print(ar[3:])
#특정 시작위치부터 특정위치까지
print(ar[:3])  #3번은 포함되지않습니다.

#일반적인 인덱싱은 데이터에 대한 뷰
ar[0] = 3000
print(ar)

xr = ar[0:3]
xr[0] = 2000
print(ar)

#복제를 하고자 하면 인덱싱 한 후 copy()를 호출해야 한다
xr = ar[0:3].copy()
xr[0] = 1000
print(ar)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
8
8
[ 6  7  8  9 10]
[400 500]
[100 200 300]
[3000  200  300  400  500]
[2000  200  300  400  500]
[2000  200  300  400  500]


Fancy Indexing

In [14]:
import numpy as n

ar = np.array([100, 200, 300, 400, 500])

#범위 대신에 list를 이용해서 인덱싱 - Fancy Indexing
xr = ar[[0, 2, 4]]
print(xr)

#Fancy Indexing은 복제를 수행한다
xr[0] = 20000
print(ar)

[100 300 500]
[100 200 300 400 500]


랜덤한 숫자 샘플링

In [16]:
import numpy as np
#0부터 4까지 비복원 추출을 이용해서 배열을 만들어서 리턴
print(np.random.permutation(5))

#seed를 고정
np.random.seed(42)

print(np.random.permutation(5))

[4 3 1 0 2]
[1 4 2 0 3]


#기본 통계 함수

In [22]:
import numpy as np

ar = np.array([10, 20, 12, 30, 40, 21, 31, 23])

br = ar.reshape(4, 2)

print(ar)
print(br)

print("합계:", np.sum(ar))
#데이터 개수로 나눈 값: 수학에서 사용
print("표준편차(자유도 적용 안함):", np.std(ar))
#데이터 개수 -1로 나눈 값: 통계학에서 사용
print("표준편차(자유도 1 적용):", np.std(ar, ddof=1))
#3사분위 수 구하기
print("3사분위 수:", np.percentile(ar, 75))


#2차원 배열
print("최대값:", np.max(br))
#행과 열 단위로 최대값 구하기
print("최대값:", np.max(br, axis=0))
print("최대값:", np.max(br, axis=1))
#결과를 원래 데이터의 차원인 2차원으로 만들어서 리턴
print("최대값:", np.max(br, axis=0, keepdims=true))

[10 20 12 30 40 21 31 23]
[[10 20]
 [12 30]
 [40 21]
 [31 23]]
합계: 187
표준편차(자유도 적용 안함): 9.379998667377304
표준편차(자유도 1 적용): 10.027640371920576
3사분위 수: 30.25
최대값: 40
최대값: [40 30]
최대값: [20 30 40 31]


NameError: name 'true' is not defined

배열 통계

In [30]:
import numpy as np

ar = np.array([10, 20, 12, 30, 40, 21, 31, 23])

print("최대값:", np.max(ar))
print("최대값의 위치:", np.argmax(ar))

br = np.array([10, 20, 12, 30, 40, 21, 31, 23])
print(br.dtype)
print("누적합:", np.cumsum(ar))
#원본 데이터 개수보다 차분을 할때마다 1개씩 결과가 줄어듭니다.
print("1차 차분:", np.diff(ar))
print("1차 차분:", np.diff(ar)/ar[0])
print("2차 차분:", np.diff(ar, n=2))

br = np.array([10, 20, 12, None, 40, 21, 31, 23])
print(br.dtype)             

최대값: 40
최대값의 위치: 4
int32
누적합: [ 10  30  42  72 112 133 164 187]
1차 차분: [ 10  -8  18  10 -19  10  -8]
1차 차분: [ 1.  -0.8  1.8  1.  -1.9  1.  -0.8]
2차 차분: [-18  26  -8 -29  29 -18]
object


where

In [35]:
import numpy as np
ar = np.array([1, 2, 3, 4])
br = np.array([10, 20, 30, 40])

condition = np.array([True, False, False, True])

#True인 경우는 ar의 데이터를 가져오고 False인 경우는 br의 데이터를 가져옴
print(np.where(condition, ar, br))


[ 1 20 30  4]


집합 관련 함수

In [39]:
import numpy as np
ar = np.array([1, 2, 3, 4, 1])
br = np.array([10, 2, 3, 40])

#중복 제거
print(np.unique(ar))

#ar에는 존재하고 br에는 없는 데이터
print(np.setdiff1d(ar, br))
#ar, br 중 한쪽에만 존재하는 데이터
print(np.setxor1d(ar, br))

[1 2 3 4]
[1 4]
[ 1  4 10 40]


정렬

In [38]:
import numpy as np
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

In [43]:
import numpy as np

ar = np.array([10, 30, 20, 50])

br = np.sort(ar)
print(br)

#내림차순
#역순으로 접근하고자 하는 경우 list 같은 경우는 reverse 함수를 이용하지만 
#ndarray는 인덱싱을 이용
cr = np.sort(ar)[::-1]
print(cr)

#정렬 알고리즘 설정
#알고리즘 테스트를 위해서 정렬을 공부할 때는
#selection, bubble, insertion, quick, merge, heap 정렬을 해두는 것이 좋음
dr = np.sort(ar, kind='mergesort')[::-1]
print(dr)

[10 20 30 50]
[50 30 20 10]
[50 30 20 10]


배열 분할 - split

In [46]:
import numpy as np
ar = np.array(range(1, 17)).reshape(4, -1)
print(ar)

#기본적으로 행방향으로 분할
ar_split = np.split(ar, 2)
print(ar_split)

#열 방향으로 분할
ar_split = np.split(ar, 2, axis=1)
print(ar_split)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


배열 합치기

In [48]:
#concatenate

import numpy as np

ar = np.array([1,2,3,4])
br = np.array([5,6,7,8])

cr = np.concatenate((ar, br))
print(cr)

#1차원 배열은 axis가없음
#dr = np.concatenate((ar,br), axis=1)
#print(dr)

[1 2 3 4 5 6 7 8]


데이터 저장과 읽기 - 중요, 확장자 확인

In [53]:
import numpy as np

ar = np.array([1, 2, 3, 4])
br = np.array([5, 6, 7, 8])

#하나의 데이터ㅓ 저장
np.save('c://programming/python/data/pratice.npy', ar)
#여러개의 데이터를 저장하고자 할때는 이름과 함께 설정
np.savez('c://programming/python/data/pratices.npy', ar=ar, br=br)
#읽어오기
xr = np.load('c://programming/python/data/pratice.npy')
print(xr)
xr = np.load('c://programming/python/data/pratices.npy.npz')
print(xr)
#여러 개를 저장한 경우에는 이름이 인덱스가 된다
print(xr['br'])

[1 2 3 4]
[5 6 7 8]
